local utils = require('utils')

utils.map('n', '<Up>', '')
utils.map('n', '<Down>', '')
utils.map('n', '<Left>', '')
utils.map('n', '<Right>', '')
utils.map('n', '<BS>', '')
utils.map('n', '<Del>', '')
utils.map('i', '<Up>', '')
utils.map('i', '<Down>', '')
utils.map('i', '<Left>', '')
utils.map('i', '<Right>', '')
-- utils.map('i', '<BS>', '')
-- utils.map('i', '<Del>', '')

-- for quickfix windows and location list
utils.map('n', '<leader>cw', '<cmd>copen<CR>', {silent = true, nowait = true})
utils.map('n', '<leader>cc', '<cmd>cclose<CR>', {silent = true, nowait = true})
utils.map('n', '<leader>lw', '<cmd>lopen<CR>', {silent = true, nowait = true})
utils.map('n', '<leader>lc', '<cmd>lclose<CR>', {silent = true, nowait = true})
utils.map('n', ']q', '<cmd>cnext<CR>', {silent = true, nowait = true})
utils.map('n', '[q', '<cmd>cprev<CR>', {silent = true, nowait = true})
utils.map('n', '[Q', '<cmd>cfirst<CR>', {silent = true, nowait = true})
utils.map('n', ']Q', '<cmd>clast<CR>', {silent = true, nowait = true})
utils.map('n', ']l', '<cmd>lnext<CR>', {silent = true, nowait = true})
utils.map('n', '[l', '<cmd>lprev<CR>', {silent = true, nowait = true})
utils.map('n', '[L', '<cmd>lfirst<CR>', {silent = true, nowait = true})
utils.map('n', ']L', '<cmd>llast<CR>', {silent = true, nowait = true})